apiVersion: apps/v1
kind: Deployment
metadata:
  name: [[forms[0].Deployment_Name]]
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
spec:
  replicas: [[forms[0].Replicas]]
  selector:
    matchLabels:
      [[forms[0].Key]] : [[forms[0].Value]]
  template:
    metadata:
      labels:
        [[forms[0].Key]] : [[forms[0].Value]]
    spec:
    containers:
      - image: [[forms[0].image]]
        name: [[forms[0].Pod_Name]]
        resources: {}